### ISSUE TITLE
Make Ideas UseCase1_1 run

### ISSUE THREAD

**Issue by PRemmen** [EnEff-BIM/EnEffBIM_UseCases#3]
see title. Changes needed in SimInfoManager and Material of the walls

**Comment by thorade** [comment]
OK, I copied the file
`EnEff-BIM_UseCases\Modelica\UseCases\Resources\Koeln_60.txt`  to
`EnEff-BIM_UseCases\Modelica\IDEAS\Inputs\Koeln_60.txt`.

But I still get 10 errors.
Do I need to do anything else?

**Comment by thorade** [comment]
Ah, sorry. I forgot to checkout the Ideas branch.
Now the model seems to be correct, just some path problems.

**Comment by PRemmen** [comment]
I'm not really sure but I guess one requirement of IDEAS is that the current directory has to be the IDEAS folder (Otherwise the relative path "/../Inputs/ " wouldn't work) have you tried that? In addition the inner loads combi time table has also an absolute path.

**Comment by thorade** [comment]
fixed by 3513564de48ae4edabb363f639b2028483651e89
using a quick and dirty solution
maybe we can find a more clean solution later
