### ISSUE TITLE
Buildings weather file

### ISSUE THREAD

**Issue by thorade** [EnEff-BIM/EnEffBIM_UseCases#4]
add the correct weather file in the correct location

**Comment by thorade** [comment]
Does not work for me:
```
The following was detected at time: 0
Cannot resolve modelica-URI after compilation, just returning string
The stack of functions is:
Buildings.BoundaryConditions.WeatherData.BaseClasses.getAbsolutePath.loadResource
Buildings.BoundaryConditions.WeatherData.BaseClasses.getAbsolutePath
Buildings.BoundaryConditions.WeatherData.BaseClasses.getHeaderElementTMY3
Buildings.BoundaryConditions.WeatherData.BaseClasses.getLongitudeTMY3
Buildings.BoundaryConditions.WeatherData.BaseClasses.getLongitudeTMY3(weaDat.filNam)
modelica://Buildings/D:/EnEff-BIM/UseCaseEnEffBIM/Utilities/Buildings/DEU_Koln.105130_IWEC.mos
```

**Comment by PRemmen** [comment]
Its probably because of the path to the Weather file itself. Following commit doesn't work for me, but at least it should point out the problem. I always have some trouble with absolute and relative pathes in Modelica

**Comment by thorade** [comment]
Yes, I got it to work.
Will commit a fix to it in a couple of minutes (directly to the master).

**Comment by thorade** [comment]
Modelica.Utilities.Files.loadResource("modelica://UseCases/Resources/InnerLoads.txt"))
